export interface CommandMapping {
  id: string;
  chinese: string;
  pinyin: string;
  arabic: string;
  english: string;
  keywords: string[];
}

export const COMMAND_DATABASE: CommandMapping[] = [
  // 1. Body & Exterior
  {
    id: 'open_sunroof',
    chinese: '打开天窗',
    pinyin: 'Dǎkāi tiānchuāng',
    arabic: 'افتح فتحة السقف',
    english: 'Open Sunroof',
    keywords: ['فتحة السقف', 'sunroof', 'افتح الفتحة', 'open sunroof', 'فتح السقف'],
  },
  {
    id: 'close_sunroof',
    chinese: '关闭天窗',
    pinyin: 'Guānbì tiānchuāng',
    arabic: 'اقفل فتحة السقف',
    english: 'Close Sunroof',
    keywords: ['اقفل فتحة السقف', 'close sunroof', 'سكر الفتحة', 'اغلق السقف'],
  },
  {
    id: 'open_windows',
    chinese: '打开车窗',
    pinyin: 'Dǎkāi chēchuāng',
    arabic: 'افتح الشبابيك',
    english: 'Open Windows',
    keywords: ['افتح الشبابيك', 'open windows', 'افتح الشباك', 'نزل الشبابيك', 'فتح النوافذ', 'افتح كل الشبابيك', 'نزل كل الشبابيك'],
  },
  {
    id: 'close_windows',
    chinese: '关闭车窗',
    pinyin: 'Guānbì chēchuāng',
    arabic: 'اقفل الشبابيك',
    english: 'Close Windows',
    keywords: ['اقفل الشبابيك', 'close windows', 'سكر الشبابيك', 'ارفع الشبابيك', 'اغلق النوافذ', 'اقفل كل الشبابيك', 'سكر كل الشبابيك', 'اغلاق كل الشبابيك'],
  },
  {
    id: 'open_front_window',
    chinese: '打开前车窗',
    pinyin: 'Dǎkāi qián chēchuāng',
    arabic: 'افتح الشباك الأمامي',
    english: 'Open Front Window',
    keywords: ['الشباك الأمامي', 'front window', 'افتح الشباك القدام', 'افتح الشباك الامامي'],
  },
  {
    id: 'close_front_window',
    chinese: '关闭前车窗',
    pinyin: 'Guānbì qián chēchuāng',
    arabic: 'اقفل الشباك الأمامي',
    english: 'Close Front Window',
    keywords: ['اقفل الشباك الأمامي', 'close front window', 'سكر الشباك الامامي', 'اغلق الشباك الامامي', 'اغلق الشباك الأمامي'],
  },
  {
    id: 'open_rear_window',
    chinese: '打开后车窗',
    pinyin: 'Dǎkāi hòu chēchuāng',
    arabic: 'افتح الشباك الخلفي',
    english: 'Open Rear Window',
    keywords: ['الشباك الخلفي', 'rear window', 'افتح الشباك اللي ورا', 'افتح الشباك الخلفي'],
  },
  {
    id: 'close_rear_window',
    chinese: '关闭后车窗',
    pinyin: 'Guānbì hòu chēchuāng',
    arabic: 'اقفل الشباك الخلفي',
    english: 'Close Rear Window',
    keywords: ['اقفل الشباك الخلفي', 'close rear window', 'سكر الشباك الخلفي', 'اغلق الشباك الخلفي'],
  },
  {
    id: 'fold_mirrors',
    chinese: '收起后视镜',
    pinyin: 'Shōuqǐ hòushìjìng',
    arabic: 'ضم المرايات',
    english: 'Fold Mirrors',
    keywords: ['ضم المرايات', 'fold mirrors', 'طبق المرايات', 'صفط المرايات'],
  },
  {
    id: 'unfold_mirrors',
    chinese: '展开后视镜',
    pinyin: 'Zhǎnkāi hòushìjìng',
    arabic: 'افتح المرايات',
    english: 'Unfold Mirrors',
    keywords: ['افتح المرايات', 'unfold mirrors', 'افرد المرايات'],
  },
  {
    id: 'open_trunk',
    chinese: '打开后备箱',
    pinyin: 'Dǎkāi hòubèixiāng',
    arabic: 'افتح الشنطة',
    english: 'Open Trunk',
    keywords: ['افتح الشنطة', 'open trunk', 'افتح الدبة', 'فتح الصندوق'],
  },
  {
    id: 'close_trunk',
    chinese: '关闭后备箱',
    pinyin: 'Guānbì hòubèixiāng',
    arabic: 'اقفل الشنطة',
    english: 'Close Trunk',
    keywords: ['اقفل الشنطة', 'close trunk', 'سكر الشنطة', 'اغلق الصندوق'],
  },
  {
    id: 'unlock_doors',
    chinese: '解锁车门',
    pinyin: 'Jiěsuǒ chēmén',
    arabic: 'افتح الأبواب',
    english: 'Unlock Doors',
    keywords: ['افتح الأبواب', 'unlock doors', 'افتح الباب', 'فتح القفل'],
  },
  {
    id: 'lock_doors',
    chinese: '锁车门',
    pinyin: 'Suǒ chēmén',
    arabic: 'اقفل الأبواب',
    english: 'Lock Doors',
    keywords: ['اقفل الأبواب', 'lock doors', 'سكر الباب', 'قفل الابواب'],
  },

  // 2. HVAC & Climate
  {
    id: 'ac_on',
    chinese: '打开空调',
    pinyin: 'Dǎkāi kōngtiáo',
    arabic: 'شغل التكييف',
    english: 'Turn on AC',
    keywords: ['شغل التكييف', 'turn on ac', 'شغل المكيف', 'تبريد'],
  },
  {
    id: 'ac_off',
    chinese: '关闭空调',
    pinyin: 'Guānbì kōngtiáo',
    arabic: 'اقفل التكييف',
    english: 'Turn off AC',
    keywords: ['اقفل التكييف', 'turn off ac', 'بند المكيف', 'طفي المكيف', 'اوقف التكييف', 'وقف التكييف', 'اوقف المكيف', 'وقف المكيف', 'اغلق التكييف', 'اغلق المكيف', 'سكر التكييف'],
  },
  {
    id: 'temp_up',
    chinese: '升高温度',
    pinyin: 'Shēnggāo wēndù',
    arabic: 'ارفع الحرارة',
    english: 'Increase Temperature',
    keywords: ['ارفع الحرارة', 'increase temperature', 'دفيني', 'زود الحرارة'],
  },
  {
    id: 'temp_down',
    chinese: '降低温度',
    pinyin: 'Jiàngdī wēndù',
    arabic: 'خفض الحرارة',
    english: 'Decrease Temperature',
    keywords: ['خفض الحرارة', 'decrease temperature', 'برد الجو', 'نزل الحرارة'],
  },
  {
    id: 'max_cooling',
    chinese: '最大制冷',
    pinyin: 'Zuìdà zhìlěng',
    arabic: 'برودة قصوى',
    english: 'Maximum Cooling',
    keywords: ['برودة قصوى', 'maximum cooling', 'تبريد عالي', 'اقوى تبريد'],
  },
  {
    id: 'temp_16',
    chinese: '温度16度',
    pinyin: 'Wēndù shíliù dù',
    arabic: 'درجة 16',
    english: 'Temperature 16',
    keywords: ['درجة 16', 'temperature 16', 'ستة عشر'],
  },
  {
    id: 'temp_20',
    chinese: '温度20度',
    pinyin: 'Wēndù èrshí dù',
    arabic: 'درجة 20',
    english: 'Temperature 20',
    keywords: ['درجة 20', 'temperature 20', 'عشرين'],
  },
  {
    id: 'temp_24',
    chinese: '温度24度',
    pinyin: 'Wēndù èrshísì dù',
    arabic: 'درجة 24',
    english: 'Temperature 24',
    keywords: ['درجة 24', 'temperature 24', 'اربعة وعشرين'],
  },
  {
    id: 'fan_up',
    chinese: '增加风速',
    pinyin: 'Zēngjiā fēngsù',
    arabic: 'علي المروحة',
    english: 'Increase Fan Speed',
    keywords: ['علي المروحة', 'increase fan speed', 'قوي الهواء', 'زود المروحة'],
  },
  {
    id: 'fan_down',
    chinese: '降低风速',
    pinyin: 'Jiàngdī fēngsù',
    arabic: 'وطي المروحة',
    english: 'Decrease Fan Speed',
    keywords: ['وطي المروحة', 'decrease fan speed', 'خفف الهواء', 'نقص المروحة'],
  },
  {
    id: 'auto_ac',
    chinese: '自动空调',
    pinyin: 'Zìdòng kōngtiáo',
    arabic: 'اوتو تكييف',
    english: 'Auto AC',
    keywords: ['اوتو تكييف', 'auto ac', 'تكييف تلقائي', 'وضع الاوتو'],
  },

  // 3. Drive Modes
  {
    id: 'normal_mode',
    chinese: '普通模式',
    pinyin: 'Pǔtōng móshì',
    arabic: 'مود عادي',
    english: 'Normal Mode',
    keywords: ['مود عادي', 'normal mode', 'الوضع العادي', 'نورمال'],
  },
  {
    id: 'eco_mode',
    chinese: '经济模式',
    pinyin: 'Jīngjì móshì',
    arabic: 'مود إيكو',
    english: 'Eco Mode',
    keywords: ['مود إيكو', 'eco mode', 'توفير الطاقة', 'اقتصادي'],
  },
  {
    id: 'sport_mode',
    chinese: '运动模式',
    pinyin: 'Yùndòng móshì',
    arabic: 'مود سبورت',
    english: 'Sport Mode',
    keywords: ['مود سبورت', 'sport mode', 'الوضع الرياضي', 'رياضي'],
  },
  {
    id: 'snow_mode',
    chinese: '雪地模式',
    pinyin: 'Xuědì móshì',
    arabic: 'مود الثلج',
    english: 'Snow Mode',
    keywords: ['مود الثلج', 'snow mode', 'وضع الثلج', 'ثلجي'],
  },
  {
    id: 'high_regen',
    chinese: '強能量回收',
    pinyin: 'Qiáng néngliàng huíshōu',
    arabic: 'استرداد قوي',
    english: 'High Regeneration',
    keywords: ['استرداد قوي', 'high regeneration', 'قوة الشحن', 'استرجاع طاقة عالي'],
  },
  {
    id: 'low_regen',
    chinese: '弱能量回收',
    pinyin: 'Ruò néngliàng huíshōu',
    arabic: 'استرداد ضعيف',
    english: 'Low Regeneration',
    keywords: ['استرداد ضعيف', 'low regeneration', 'استرجاع طاقة ضعيف'],
  },

  // 4. Media & Apps
  {
    id: 'play_music',
    chinese: '播放音乐',
    pinyin: 'Bōfàng yīnyuè',
    arabic: 'شغل الموسيقى',
    english: 'Play Music',
    keywords: ['شغل الموسيقى', 'play music', 'شغل اغاني', 'شغل مقاطع'],
  },
  {
    id: 'pause_music',
    chinese: '暂停音乐',
    pinyin: 'Zàntíng yīnyuè',
    arabic: 'وقف الموسيقى',
    english: 'Pause Music',
    keywords: ['وقف الموسيقى', 'pause music', 'وقف الأغاني', 'ايقاف الموسيقى'],
  },
  {
    id: 'volume_up',
    chinese: '增大音量',
    pinyin: 'Zēngdà yīnliàng',
    arabic: 'ارفع الصوت',
    english: 'Volume Up',
    keywords: ['ارفع الصوت', 'volume up', 'علي الصوت', 'زود الصوت'],
  },
  {
    id: 'volume_down',
    chinese: '降低音量',
    pinyin: 'Jiàngdī yīnliàng',
    arabic: 'خفض الصوت',
    english: 'Volume Down',
    keywords: ['خفض الصوت', 'volume down', 'وطي الصوت', 'نقص الصوت'],
  },
  {
    id: 'open_youtube',
    chinese: '打开YouTube',
    pinyin: 'Dǎkāi YouTube',
    arabic: 'افتح يوتيوب',
    english: 'Open YouTube',
    keywords: ['افتح يوتيوب', 'open youtube', 'يوتيوب'],
  },
  {
    id: 'open_google_maps',
    chinese: '打开谷歌地图',
    pinyin: 'Dǎkāi gǔgē dìtú',
    arabic: 'افتح جوجل ماب',
    english: 'Open Google Maps',
    keywords: ['افتح جوجل ماب', 'open google maps', 'افتح الخرائط', 'قوقل ماب'],
  },
  {
    id: 'open_autokit',
    chinese: '打开Autokit',
    pinyin: 'Dǎkāi Autokit',
    arabic: 'افتح أوتوكيت',
    english: 'Open Autokit',
    keywords: ['افتح أوتوكيت', 'open autokit'],
  },
  {
    id: 'open_browser',
    chinese: '打开浏览器',
    pinyin: 'Dǎkāi liúlǎnqì',
    arabic: 'افتح المتصفح',
    english: 'Open Browser',
    keywords: ['افتح المتصفح', 'open browser', 'افتح انترنت'],
  },
  {
    id: 'navi_home',
    chinese: '导航回家',
    pinyin: 'Dǎoháng huíjiā',
    arabic: 'روح البيت',
    english: 'Navigate Home',
    keywords: ['روح البيت', 'navigate home', 'وديني البيت', 'منزل'],
  },
  {
    id: 'go_home_screen',
    chinese: '返回主界面',
    pinyin: 'Fǎnhuí zhǔ jièmiàn',
    arabic: 'الصفحة الرئيسية',
    english: 'Go to Home Screen',
    keywords: ['الصفحة الرئيسية', 'home screen', 'شاشة البداية', 'الهوم'],
  },
  {
    id: 'screen_off',
    chinese: '关闭屏幕',
    pinyin: 'Guānbì píngmù',
    arabic: 'اقفل الشاشة',
    english: 'Turn off Screen',
    keywords: ['اقفل الشاشة', 'turn off screen', 'طفي الشاشة', 'سكر الشاشة'],
  },

  // 5. Lighting & System
  {
    id: 'lights_on',
    chinese: '打开灯',
    pinyin: 'Dǎkāi dēng',
    arabic: 'شغل النور',
    english: 'Turn on Lights',
    keywords: ['شغل النور', 'turn on lights', 'شغل الضواية', 'افتح النور'],
  },
  {
    id: 'lights_off',
    chinese: '关闭车内灯',
    pinyin: 'Guānbì chēnèi dēng',
    arabic: 'اقفل النور',
    english: 'Turn off Lights',
    keywords: ['اقفل النور', 'turn off lights', 'طفي الضواية', 'سكر النور'],
  },
  {
    id: 'ambient_on',
    chinese: '打开氛围灯',
    pinyin: 'Dǎkāi fènwéidēng',
    arabic: 'شغل الأمبيانت',
    english: 'Turn on Ambient Light',
    keywords: ['شغل الأمبيانت', 'turn on ambient light', 'شغل اضاءة الصالون', 'اضاءة محيطة'],
  },
  {
    id: 'ambient_off',
    chinese: '关闭氛围灯',
    pinyin: 'Guānbì fènwéidēng',
    arabic: 'اقفل الأمبيانت',
    english: 'Turn off Ambient Light',
    keywords: ['اقفل الأمبيانت', 'turn off ambient light', 'طفي الأمبيانت'],
  },
  {
    id: 'drl_on',
    chinese: '打开日间灯',
    pinyin: 'Dǎkāi rìjiān dēng',
    arabic: 'شغل نور النهار',
    english: 'Turn on DRL',
    keywords: ['شغل نور النهار', 'turn on drl', 'انوار نهارية'],
  },
  {
    id: 'drl_off',
    chinese: '关闭日间灯',
    pinyin: 'Guānbì rìjiān dēng',
    arabic: 'اقفل نور النهار',
    english: 'Turn off DRL',
    keywords: ['اقفل نور النهار', 'turn off drl'],
  },
  {
    id: 'bluetooth_on',
    chinese: '打开蓝牙',
    pinyin: 'Dǎkāi lányá',
    arabic: 'شغل البلوتوث',
    english: 'Turn on Bluetooth',
    keywords: ['شغل البلوتوث', 'turn on bluetooth', 'تفعيل البلوتوث'],
  },
  {
    id: 'bluetooth_off',
    chinese: '关闭蓝牙',
    pinyin: 'Guānbì lányá',
    arabic: 'اقفل البلوتوث',
    english: 'Turn off Bluetooth',
    keywords: ['اقفل البلوتوث', 'turn off bluetooth'],
  },
  {
    id: 'wake_up',
    chinese: '你好，小迪',
    pinyin: 'Nǐ hǎo, xiǎo dí',
    arabic: 'مرحباً بي واي دي',
    english: 'Hello BYD',
    keywords: ['byd', 'بي واي دي', 'بي وايدي', 'hey byd', 'hello byd', 'يا سيارة', 'دي دي', 'didi', 'di di', 'ديدي'],
  }
];
